[gcp]
type = "service_account"
project_id = "dulcet-velocity-467118-c5"
private_key_id = "2448ef6939d678bcf9273b01bc3f66183044ede4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvAw70I3mk3msZ
lYEAm1YksvgLeis/+ozK5zu7r/09BaEAZAnQr6KE/f+UMP7aJVk0CiCilIV8BIGP
XXmEA14GsJR2GpK41kspWwPn+UZE+w/UgWsS7B8RAEH28/BTvh8hZAgHOo2YdgzT
uk7xYHWyEzwATEmd/5sa5HhVCRSHr2nG9X3WM5A1R/6XZ8XrUoHOkYD02NSu4xNe
apvCy+bwSf1AoAwfaL1E1wA5VdrytzjWJ0e3XSrujC3Wp/8igtXXCc3GadgmNZYc
ua7Nl/hq6p7JXXrsO9tZzVgxZqtEU6f58rhtE/63cFNA83bMZ0kGaFJokwi6Uz71
9qrwqGyXAgMBAAECggEAQcpAClX1qh00nLL/gjdizDv9E+9yp8PrvnDrmxQ++fwO
OKPirrD/wsfrFo3OmDn3DSGLgCKeBW96Nuc4QYC0jYY+4SD/K/3e1maREti56j+J
BWU7V6ssyIrUwV2VaB2t/TLp87G2vewOyV8dww50YCNr6F7FQ+BtMdBWTf0yWwjd
RJvIxKztcpk5UHEMQF139N+zU/5BREfliHa1E/OrNQwys8UcorFvU0CAZPtzvukr
Dq8HkQANCddXXvdLFouFF/45vJLyPh3lr5cLnzW+DsveAKsu86NX3uhmA5QGsVU1
uY0LiiMzGZ5s5Ih5464nHfhzhtHuMTWbuZR4rbewWQKBgQDvB+yedYAt470mzgfd
93aqmaNxc6n6iFcYrGDZbw95QrBa/IXfZ3Fftohj6WVbNYHGu9PCNwsq2aYwF95P
ts11TKnH5gNd4Y0VelaOzismfxi4gSh0VcP+E6N9NEqKEkzJdW/PYsVuwUzPLDa2
JYmQ94HAZV1/PRx+o7tCF7BxfwKBgQC7b6wU2caPPSnlHd2xf73D+CPzq4qaTVsW
ATM6v2vn/+9U7O2buTJm9+CKnyGqz8NQx7iuanTMtuQ49fvLslHsLlaB7Wxy/mhm
4/qBXWH4C7Cua1ER7SHLfgiYKJ9EftK7OLnzce30Nhx3KP2r8ionGJhHXDLnHdYO
xEsA/z7g6QKBgQDAwwAzzYgf+b+Jcq9vdmgxLhNbo64ZRygN0r2Lu3+cB4bW6TxA
rFgGmtok0IyXYHAWx1P/FIqh9MGLmUQDvuSzyq5EcZ6XcBRplK4HHgY4VlimOipY
nu2ekVHP34KZFCbudBFGCl4zchkyHXLFs0HcMW1mrZgXyz2Wdw3FP/tfmwKBgGbk
PoqTobQv1ze21WQCw6E4LkQs/sEFheLmdcDiI9IPZMox5Z1+ZHSxzclK4ahqtMU7
Xd4hAkz+ePnrznVbRi1oooRgWRAnKBiTPYiWQplvkWWt86rriYmzffRJGGT5WaT8
1tcUy5MrwSSIk/g3z3v2vGEv86F7d25TwvihJVtBAoGBAJCCiiVT6VGRCyfcTy4o
7VYB1+wGhQ3JVhE3zDpggRzPBqoYj7BMhl4nh3KurPyc4YQCU28L/Knvkz6K5mtt
Qq/nIKfD2yOwobPNw3mfSvribouslIRSZ23IkXpVsfKI2KEi0kbsTrGb0qd+WrU8
NZtwGYC4WAgl9C/0ptXMoZnh
-----END PRIVATE KEY-----"""
client_email = "panaderia-streamlit-access@dulcet-velocity-467118-c5.iam.gserviceaccount.com"
client_id = "104243457515168597866"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/panaderia-streamlit-access%40dulcet-velocity-467118-c5.iam.gserviceaccount.com"
